import type { OperationDef } from "../../src/types.js";

export const MAX_TOOL_SCHEMA_CHARS = 60000;

function sorted(ops: OperationDef[]): OperationDef[] {
  return [...ops].sort((a, b) => a.tool.localeCompare(b.tool) || a.action.localeCompare(b.action));
}

export function emitOperations(ops: OperationDef[], specVersion: string): string {
  return [
    "// GENERATED by server/scripts/codegen.ts from Gorelo's public OpenAPI spec. Do not edit by hand.",
    "// Regenerate with: npm run codegen",
    'import type { OperationDef } from "../src/types.js";',
    "",
    `export const SPEC_VERSION = ${JSON.stringify(specVersion)};`,
    "",
    `export const OPERATIONS: OperationDef[] = ${JSON.stringify(sorted(ops), null, 2)};`,
    "",
  ].join("\n");
}

export function sizeReport(ops: OperationDef[]): { tool: string; chars: number }[] {
  const byTool = new Map<string, number>();
  for (const op of ops) {
    const chars = JSON.stringify({ params: op.params, body: op.body }).length;
    byTool.set(op.tool, (byTool.get(op.tool) ?? 0) + chars);
  }
  return [...byTool].map(([tool, chars]) => ({ tool, chars })).sort((a, b) => b.chars - a.chars);
}
