import { describe, expect, it } from "vitest";
import { emitOperations, sizeReport } from "../scripts/codegen/emit.js";
import { planOperations } from "../scripts/codegen/plan.js";
import spec from "./fixtures/mini-spec.json" with { type: "json" };

const ops = planOperations(spec as never);

describe("emitOperations", () => {
  const src = emitOperations(ops, "1.0.0");

  it("emits a typed, generated-banner module", () => {
    expect(src.startsWith("// GENERATED by server/scripts/codegen.ts")).toBe(true);
    expect(src).toContain('import type { OperationDef } from "../src/types.js";');
    expect(src).toContain('export const SPEC_VERSION = "1.0.0";');
    expect(src).toContain("export const OPERATIONS: OperationDef[] = [");
  });

  it("is deterministic", () => {
    expect(emitOperations([...ops].reverse(), "1.0.0")).toBe(src);
  });

  it("matches snapshot", () => {
    expect(src).toMatchSnapshot();
  });
});

describe("sizeReport", () => {
  it("reports one row per tool, largest first", () => {
    const rows = sizeReport(ops);
    expect(rows.map((r) => r.tool)).toContain("gorelo_admin");
    expect(rows[0]!.chars).toBeGreaterThanOrEqual(rows[rows.length - 1]!.chars);
  });
});
